export const currentMsg = {
  id: "1",
  img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613435284/pmmnrbuspg9d8vl5cqqe.jpg",
  name: "Raji Mustapha",
  latestMessage: `Will like to recommend will change all the admin password every 3 month and fius ahhs ajjus ddjudm djjusu hdys sjuue s hasjs dhhsbe`,
  isActive: true,
  msgList: [
    {
      id: "1",
      msg: "Will like to recommend will change all the admin password every 3 month and",
      time: 20120620,
      senderId: "2323",
    },
    {
      id: "2",
      msg: "yes you can 3 month and",
      time: 201620,
      senderId: "1234",
    },
    {
      id: "3",
      msg: "Will likei am not vcoming anywhere very 3 month and",
      time: 20122323320620,
      senderId: "2323",
    },
    {
      id: "4",
      msg: "Will like jus djys paos the admin password every 3 month and",
      time: 201232120620,
      senderId: "1234",
    },
    {
      id: "1",
      msg: "Will like to recommend will change all the admin password every 3 month and",
      time: 20120620,
      senderId: "2323",
    },
    {
      id: "2",
      msg: "yes you can 3 month and",
      time: 201620,
      senderId: "1234",
    },
    {
      id: "3",
      msg: "Will likei am not vcoming anywhere very 3 month and",
      time: 20122323320620,
      senderId: "2323",
    },
    {
      id: "4",
      msg: "Will like jus djys paos the admin password every 3 month and",
      time: 201232120620,
      senderId: "1234",
    },
    {
      id: "1",
      msg: "Will like to recommend will change all the admin password every 3 month and",
      time: 20120620,
      senderId: "2323",
    },
    {
      id: "2",
      msg: "yes you can 3 month and",
      time: 201620,
      senderId: "1234",
    },
    {
      id: "3",
      msg: "Will likei am not vcoming anywhere very 3 month and",
      time: 20122323320620,
      senderId: "2323",
    },
    {
      id: "4",
      msg: "Will like jus djys paos the admin password every 3 month and",
      time: 201232120620,
      senderId: "1234",
    },
  ],
};
export const messageBoxList = [
  {
    id: "1",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613435284/pmmnrbuspg9d8vl5cqqe.jpg",
    name: "Raji Mustapha",
    latestMessage: `Will like to recommend will change all the admin password every 3 month and fius ahhs ajjus ddjudm djjusu hdys sjuue s hasjs dhhsbe`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "2",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "3",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613435284/pmmnrbuspg9d8vl5cqqe.jpg",
    name: "Raji Mustapha",
    latestMessage: `Will like to recommend will change all the admin password every 3 month and fius ahhs ajjus ddjudm djjusu hdys sjuue s hasjs dhhsbe`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "4",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "5",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "6",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "7",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "8",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "9",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "10",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
  {
    id: "11",
    img: "https://res.cloudinary.com/dpiyqfdpk/image/upload/v1613490335/m1yqdkd2vjuuh2tss0aq.jpg",
    name: "Raji Toyin",
    latestMessage: `I Will like to recommend will change all the admin password every 3 momn jnj jjhh hhh jkii kjn  hgy kjj hyy hh gc uyu jhju kjn jhb jhyubg jhb`,
    numberOfNew: 5,
    time: 20120620,
  },
];
